name: Trigger auto deployment for antpsci

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/antpsci-AutoDeployTrigger-995826a0-0c9c-46ce-91c1-300e0bc3093e.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANTPSCI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: antuxtest.azurecr.io
          registryUsername: ${{ secrets.ANTPSCI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANTPSCI_REGISTRY_PASSWORD }}
          containerAppName: antpsci
          resourceGroup: antpsmay
          imageToBuild: antuxtest.azurecr.io/antpsci:${{ github.sha }}
          

     

