name: Trigger auto deployment for antpsci

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/antpsci-AutoDeployTrigger-753d1b19-f0fc-4892-8655-3a7cd9344f9a.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANTPSCI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: appsvcbuildacr1.azurecr.io
          registryUsername: ${{ secrets.ANTPSCI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANTPSCI_REGISTRY_PASSWORD }}
          containerAppName: antpsci
          resourceGroup: antpsmay
          imageToBuild: appsvcbuildacr1.azurecr.io/antpsci:${{ github.sha }}
          

     

