name: Trigger auto deployment for antps23

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/antps23-AutoDeployTrigger-262bd028-e821-45f4-9da2-e534145ba63f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: antuxtest.azurecr.io
          username: ${{ secrets.ANTPS23_REGISTRY_USERNAME }}
          password: ${{ secrets.ANTPS23_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: antuxtest.azurecr.io/antps23:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANTPS23_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n antps23 -g Test_carg_WestUS --server antuxtest.azurecr.io --username  ${{ secrets.ANTPS23_REGISTRY_USERNAME }} --password ${{ secrets.ANTPS23_REGISTRY_PASSWORD }}
            az containerapp update -n antps23 -g Test_carg_WestUS --image antuxtest.azurecr.io/antps23:${{ github.sha }}
