name: Trigger auto deployment for antpssep

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/antpssep-AutoDeployTrigger-547f13a5-2a90-4230-b71c-b0a230921d9d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANTPSSEP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryu7gqusdmw6cko.azurecr.io
          registryUsername: ${{ secrets.ANTPSSEP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANTPSSEP_REGISTRY_PASSWORD }}
          containerAppName: antpssep
          resourceGroup: antpsaug
          imageToBuild: containerregistryu7gqusdmw6cko.azurecr.io/antpssep:${{ github.sha }}
          

     

