name: Trigger auto deployment for containerapr

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/containerapr-AutoDeployTrigger-93a661fe-7907-4a62-8a1d-0dd1f4c7631e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: taskstrackeracr1.azurecr.io
          username: ${{ secrets.CONTAINERAPR_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: taskstrackeracr1.azurecr.io/containerapr:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapr -g Apr_Rg --server taskstrackeracr1.azurecr.io --username  ${{ secrets.CONTAINERAPR_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPR_REGISTRY_PASSWORD }}
            az containerapp update -n containerapr -g Apr_Rg --image taskstrackeracr1.azurecr.io/containerapr:${{ github.sha }}
