name: Trigger auto deployment for containerappjune

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/containerappjune-AutoDeployTrigger-77cdd9a1-1aef-46cf-98d9-db33198206a1.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPJUNE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: taskstrackeracr1.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPJUNE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJUNE_REGISTRY_PASSWORD }}
          containerAppName: containerappjune
          resourceGroup: container_June
          imageToBuild: taskstrackeracr1.azurecr.io/containerappjune:${{ github.sha }}
          

     

