name: Trigger auto deployment for testingantps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ GitTesting ]
    paths:
    - '**'
    - '.github/workflows/testingantps-AutoDeployTrigger-b545b69f-4494-4bda-abe2-315f66ccb96f.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTINGANTPS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: antuxtest.azurecr.io
          registryUsername: ${{ secrets.TESTINGANTPS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTINGANTPS_REGISTRY_PASSWORD }}
          containerAppName: testingantps
          resourceGroup: antpsmay
          imageToBuild: antuxtest.azurecr.io/testingantps:${{ github.sha }}
          

     

